Refactor get-github-issues script and add configuration handling
- Changed shebang to use '/usr/bin/env bash' for better portability.
- Added usage information and licensing details to the script header.
- Implemented sourcing of 'github-config' for configuration management.
- Added error handling for missing configuration file and unset 'GITHUB_TOKEN'.

Refactor ANSI color codes to use tput variables in scripts

- Replaced direct ANSI escape codes with tput variables (BOLD, RESET) for
  consistent formatting.
- Improved script readability and maintainability.

Improve script clarity and usage examples

- Fixed issue with 'download-commit-plain-diff' command output file naming.
- Enhanced usage documentation for 'issue-keys', 'download-repository', 'x',
  'root', and 'root-relative' commands.
- Updated 'issue-keys' command to use 'grep' for regex matching.

diff --git a/bin/get-github-issues b/bin/get-github-issues
--- a/bin/get-github-issues
+++ b/bin/get-github-issues
@@ -1,7 +1,27 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
-# Set your GitHub Personal Access Token here.
-GITHUB_TOKEN="..."
+#? get-github-issues, Time-stamp: <2024-09-19 Thu 11:04>
+#? Copyright (C) 2024 Fabrice Niessen
+#?
+#? License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
+#? This is free software: you are free to change and redistribute it.
+#? There is NO WARRANTY, to the extent permitted by law.
+
+##? Usage: get-github-issues [options]
+
+# Source the configuration file.
+if [ -f "~/bin/github-config" ]; then
+    source ~/bin/github-config
+else
+    printf >&2 "Error: Configuration file github-config not found.\n"
+    exit 2
+fi
+
+# Check if required environment variable is set.
+if [ -z "$GITHUB_TOKEN" ]; then
+    printf >&2 "Error: GITHUB_TOKEN environment variable must be set.\n"
+    exit 2
+fi
 
 # Get the remote URL for the 'origin' remote.
 remote_url=$(git remote get-url origin)
