Add error-handling when pushing

diff --git a/bin/git-push-all-repos b/bin/git-push-all-repos
--- a/bin/git-push-all-repos
+++ b/bin/git-push-all-repos
@@ -13,16 +13,21 @@ printf "Searching at most 5 levels of directories...\n"
 # Handle directories with spaces in the find command.
 while IFS=$'\n' read -r repo_path; do
     printf 'Updating repository %s:\n' "${bold}$repo_path${reset}"
+    remote_url=$(git -C "$repo_path" config --get remote.origin.url)
     if git -C "$repo_path" rev-parse --quiet --verify @{u} >/dev/null 2>&1; then
         if git -C "$repo_path" diff --quiet @{u} &>/dev/null; then
             printf "No changes to push\n"
         else
             printf "Changes found:\n"
             git -C "$repo_path" log --date=short @{u}..
-            git -C "$repo_path" push
+            # Make sure push is successful before continuing to next repo.
+            if git -C "$repo_path" push; then
+                printf "Push to %s was successful\n" "$remote_url"
+            else
+                printf >&2 "Error: Push to %s failed\n" "$remote_url"
+            fi
         fi
     else
-        remote_url=$(git -C "$repo_path" config --get remote.origin.url)
         printf >&2 "Error: remote repository '%s' is not accessible or authentication failed\n" "$remote_url"
     fi
     printf "\n"
