Fix error message

diff --git a/bin/git-switch-ssh-to-https b/bin/git-switch-ssh-to-https
--- a/bin/git-switch-ssh-to-https
+++ b/bin/git-switch-ssh-to-https
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
 #? git-switch-ssh-to-https, Time-stamp: 20221102.1443
-#? Copyright (C) 2013-2023 Fabrice Niessen
+#? Copyright (C) 2022-2023 Fabrice Niessen
 #?
 #? License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
 #? This is free software: you are free to change and redistribute it.
@@ -35,7 +35,7 @@ OLD_URL=$(git remote -v | awk -v REMOTE="$REMOTE" '$1==REMOTE && $3=="(push)" {p
 
 # Check if the old URL is valid.
 if [[ -z "$OLD_URL" ]]; then
-    printf >&2 "Error: Could not identify Repo URL. It's possible that the repo is already using HTTPS instead of SSH.\n"
+    printf >&2 "Error: Could not identify Repo URL.\n"
     exit 2
 fi
 
@@ -45,7 +45,7 @@ REPO_SLUG=$(echo "$OLD_URL" | sed -Ene"s#git@$SITE[^:]*:([^/]*)/(.*).git#\2#p")
 
 # Check if the repo owner and name are valid.
 if [[ -z "$REPO_OWNER" ]] || [[ -z "$REPO_SLUG" ]]; then
-    printf >&2 "Error: Could not identify Repo Owner or Slug.\n"
+    printf >&2 "Error: Could not identify Repo Owner or Slug. It's possible that the repo is already using HTTPS instead of SSH.\n"
     exit 2
 fi
 
