Improve Docopt block of code

diff --git a/bin/git-is-ancestor b/bin/git-is-ancestor
--- a/bin/git-is-ancestor
+++ b/bin/git-is-ancestor
@@ -22,13 +22,21 @@
 ##? Example:
 ##?   git-is-ancestor 71031cec HEAD determine if current branch contains the commit
 
-# Check if docopts command is available.
-command -v docopts > /dev/null 2>&1 || { printf >&2 'Error: docopts command not found.\n'; exit 2; }
+set -euo pipefail
 
+# Check if docopts command is available.
+if ! command -v docopts > /dev/null 2>&1; then
+    printf >&2 'Error: docopts command not found.\n'
+    exit 2
+fi
+
+# Extract help and version information from the script.
 help=$(grep "^##?" "$0" | cut -c 5-)
-version=$(grep "^#?"  "$0" | cut -c 4-)
-parsed="$(docopts -h "$help" -V "$version" : "$@")"
-eval "$parsed"
+version=$(grep "^#?" "$0" | cut -c 4-)
+
+# Get command-line arguments.
+args="$(docopts -h "$help" -V "$version" : "$@")"
+eval "$args"
 
 # Check if one commit is an ancestor of the other.
 if git merge-base --is-ancestor "$COMMIT_1" "$COMMIT_2"; then
