Add docopts

diff --git a/bin/git-find-recent-branches b/bin/git-find-recent-branches
--- a/bin/git-find-recent-branches
+++ b/bin/git-find-recent-branches
@@ -1,8 +1,48 @@
 #!/usr/bin/env bash
 
-# Set the default threshold (7 days ago) or use the first argument if provided.
-threshold_days=${1:-7}
-threshold_date=$(date -d "$threshold_days days ago" +%Y-%m-%d)
+#? git-find-recent-branches, Time-stamp: 20221102.1443
+#? Copyright (C) 2024 Fabrice Niessen
+#?
+#? License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
+#? This is free software: you are free to change and redistribute it.
+#? There is NO WARRANTY, to the extent permitted by law.
+
+##? Usage: git-find-recent-branches [options] [THRESHOLD]
+##?
+##? Find Git branches modified recently.
+##?
+##? Arguments:
+##?   THRESHOLD                     specify the threshold in days [default: 7].
+##?
+##? Options:
+##?   -h, --help                    display this help and exit
+##?   -V, --version                 display version information and exit
+
+# Set -uo pipefail for undefined variable check and pipeline failure propagation.
+set -uo pipefail
+
+# Check if docopts command is available.
+if ! command -v docopts > /dev/null 2>&1; then
+    printf >&2 'Error: docopts command not found.\n'
+    exit 2
+fi
+
+# Extract help and version information from the script.
+help=$(grep "^##?" "$0" | cut -c 5-)
+version=$(grep "^#?" "$0" | cut -c 4-)
+
+# Get command-line arguments.
+args="$(docopts -h "$help" -V "$version" : "$@")"
+eval "$args"
+
+# Set -e to exit on non-zero command status.
+set -e
+
+# Set the threshold.
+THRESHOLD=${1:-7}
+
+# Convert threshold to date format.
+threshold_date=$(date -d "$THRESHOLD days ago" +%Y-%m-%d)
 
 # Fetch remote branches and filter by last commit date.
 git fetch --prune
